version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quotes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=quotes_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=django-insecure-local-development-key-change-in-production
      - DJANGO_SETTINGS_MODULE=quotes_project.settings
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py populate_quotes &&
             daphne -b 0.0.0.0 -p 8000 quotes_project.asgi:application"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: