version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quotes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - quotes_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - quotes_network

  backend:
    build: ./backend
    environment:
      - DEBUG=False
      - DB_NAME=quotes_db
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD:-secure_password_change_me}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=${DJANGO_SECRET_KEY:-change-me-in-production}
      - DJANGO_SETTINGS_MODULE=quotes_project.settings
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - quotes_network
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py populate_quotes &&
             daphne -b 0.0.0.0 -p 8000 quotes_project.asgi:application"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - quotes_network

volumes:
  postgres_data:

networks:
  quotes_network:
    driver: bridge